# -*- mode: ruby -*-
# vi: set ft=ruby :

# README
#
# Getting Started:
# 1. vagrant plugin install vagrant-hostmanager
# 2. vagrant up
# 3. vagrant ssh
#
# This should put you at the control host
#  with access, by name, to other vms
Vagrant.configure(2) do |config|
  config.hostmanager.enabled = true
  config.vm.box = "centos/7"
  config.hostmanager.manage_host = true

  config.vm.define "lab02centos7" do |h|
    h.vm.provider :virtualbox do |vb|
    #    vb.name = "docker012"
		vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    h.vm.network "private_network", ip: "192.168.135.132"
    #h.vm.provision "shell", path: "scripts/install_docker.sh"
    h.vm.hostname = "lab02centos7"
  end
  
  

end
